language: node_js
node_js:
  - lts/dubnium
  - node
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: m9QiTIk434cWw3cZnsYHcM785vhUoCkZQTgwuTIhvOFQbl5x3s7R9dDhO6HHH+fvFUbSM0htamzKzOEqsT9ixcbGwD3WcTr++bAx2deNigZdL+t8ukndt2JXf926gANrS09Au7fv8PI8UyV8CfLidFkwVVOrqTWMFZGt0x16S4aXKIL+pv67qhrAAbtgsb1/haxSH76ECIJj9QoDXn4zs9wW5YIjwP0etdnmSA8Xx7Wo5OU+v6Igc8TZMVzz0JXRXQ9VyYZUz4USAbuzZXmjENm/SsP07tOuDftz///sd6VjgcmOKNT9O3kbLeLZSvRLkXysoIyKWdCP0fXmei7+Qx6vHpgQLEWIiQ6jUln4hvPNEK8wGVimtE0YuvmdhNSH0C9c5yWx/77dUqzb6w4WQubIBGbw0RS652aNLOioFpar4srEixjbEpHgLNdI3idA0ZaYXDewlgJ1nylZWuPa7JTKU3Uu2wRp6AcIuaRcA4/wYL0XstuhpW+3XMcyetjP72/DyyynmLLYFeQ5aj9B6TDS088XumcylOH5sk+MLU8UjzTxTosnFyzjil3+WtvJ5nlxCuOBE2cOjr09mV1fgCE4+Nm8IMdLSI3YHeZYYrvOmCDeL1Y8BF3sG3Ux18a864nf8bdyZhpR0xnaKPqPDMq3gI2rRLxPNMLLD3sWpmY=
  file:
    - 'bcp-47.js'
    - 'bcp-47.min.js'
  on:
    tags: true
    node: 'node'
